-- jobs.sql

USE job_search_app; -- データベース名に合わせて変更してください

DROP TABLE IF EXISTS jobs;

-- テーブルが存在しない場合は作成します
CREATE TABLE IF NOT EXISTS jobs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title_en VARCHAR(255),
    description_en TEXT,
    area_en VARCHAR(255),
    station_en VARCHAR(255),
    job_type_en VARCHAR(255),

    title_ja VARCHAR(255),
    description_ja TEXT,
    area_ja VARCHAR(255),
    station_ja VARCHAR(255),
    job_type_ja VARCHAR(255),

    is_single BOOLEAN
);

-- データの挿入
INSERT INTO jobs (title_en, description_en, area_en, station_en, job_type_en, title_ja, description_ja, area_ja, station_ja, job_type_ja, is_single) VALUES
('Cafe staff', 'Customer service and cleaning work in the cafe.', 'Tokyo', 'Shibuya', 'Food', 'カフェスタッフ', 'カフェでの接客と清掃業務', '東京', '渋谷', '飲食', 1),
('Sales staff', 'Customer service and cash register in an apparel store.', 'Osaka', 'Umeda', 'Retail', '販売スタッフ', 'アパレルショップでの接客とレジ業務', '大阪', '梅田', '小売', 0),
('Administrative assistant', 'Office paperwork and telephone support.', 'Aichi', 'Nagoya', 'Office', '事務アシスタント', 'オフィスでの書類整理と電話対応', '愛知', '名古屋', '事務', 1),
('Restaurant waiter', 'Taking orders and serving food in a restaurant.', 'Fukuoka', 'Tenjin', 'Food', 'レストラン接客係', 'レストランでの注文取りと料理提供', '福岡', '天神', '飲食', 0),
('Convenience store clerk', 'Cashier and shelf stocking in a convenience store.', 'Tokyo', 'Shinjuku', 'Retail', 'コンビニ店員', 'コンビニでのレジ打ちと商品補充', '東京', '新宿', '小売', 1),
('Data entry clerk', 'Inputting data and managing databases.', 'Osaka', 'Namba', 'Office', 'データ入力係', 'データ入力とデータベース管理', '大阪', '難波', '事務', 0),
('Sushi chef assistant', 'Preparing ingredients and assisting sushi chefs.', 'Aichi', 'Okazaki', 'Food', '寿司職人助手', '寿司の材料準備と職人の補助', '愛知', '岡崎', '飲食', 1),
('Bookstore staff', 'Organizing books and assisting customers.', 'Fukuoka', 'Hakata', 'Retail', '書店スタッフ', '本の整理と顧客対応', '福岡', '博多', '小売', 0),
('HR assistant', 'Supporting HR department with administrative tasks.', 'Tokyo', 'Akasaka', 'Office', '人事アシスタント', '人事部門の管理業務サポート', '東京', '赤坂', '事務', 1),
('Ramen shop staff', 'Cooking and serving ramen in a busy shop.', 'Osaka', 'Tennoji', 'Food', 'ラーメン店スタッフ', '忙しいラーメン店での調理と接客', '大阪', '天王寺', '飲食', 0),
('Electronics store salesperson', 'Selling electronics and providing product information.', 'Aichi', 'Toyohashi', 'Retail', '家電量販店販売員', '電化製品の販売と商品説明', '愛知', '豊橋', '小売', 1),
('Receptionist', 'Greeting visitors and managing front desk operations.', 'Fukuoka', 'Kokura', 'Office', '受付係', '来客対応とフロント業務管理', '福岡', '小倉', '事務', 0),
('Izakaya server', 'Taking orders and serving drinks in a Japanese pub.', 'Tokyo', 'Ikebukuro', 'Food', '居酒屋サーバー', '居酒屋での注文取りと飲み物提供', '東京', '池袋', '飲食', 1),
('Clothing store manager', 'Overseeing daily operations of a clothing store.', 'Osaka', 'Shinsaibashi', 'Retail', '衣料品店マネージャー', '衣料品店の日常業務管理', '大阪', '心斎橋', '小売', 0),
('Accounting clerk', 'Processing invoices and managing financial records.', 'Aichi', 'Toyota', 'Office', '経理事務員', '請求書処理と財務記録管理', '愛知', '豊田', '事務', 1),
('Bakery staff', 'Baking and selling bread and pastries.', 'Fukuoka', 'Ohori', 'Food', 'ベーカリースタッフ', 'パンとお菓子の製造販売', '福岡', '大濠', '飲食', 0),
('Supermarket cashier', 'Operating cash register and bagging groceries.', 'Tokyo', 'Kichijoji', 'Retail', 'スーパーマーケットレジ係', 'レジ操作と商品袋詰め', '東京', '吉祥寺', '小売', 1),
('Office manager', 'Coordinating office activities and managing supplies.', 'Osaka', 'Honmachi', 'Office', 'オフィスマネージャー', 'オフィス業務の調整と備品管理', '大阪', '本町', '事務', 0),
('Fast food crew member', 'Preparing and serving fast food items.', 'Aichi', 'Ichinomiya', 'Food', 'ファストフード店員', 'ファストフードの調理と提供', '愛知', '一宮', '飲食', 1),
('Department store sales associate', 'Assisting customers and maintaining store appearance.', 'Fukuoka', 'Chihaya', 'Retail', '百貨店販売員', '顧客対応と店舗外観維持', '福岡', '千早', '小売', 0),
('Executive assistant', 'Providing high-level administrative support to executives.', 'Tokyo', 'Otemachi', 'Office', '秘書', '幹部への高度な管理サポート提供', '東京', '大手町', '事務', 1),
('Soba restaurant cook', 'Preparing and cooking soba noodles.', 'Osaka', 'Kitahama', 'Food', 'そば屋調理師', 'そばの準備と調理', '大阪', '北浜', '飲食', 0),
('Mobile phone shop staff', 'Selling phones and explaining service plans.', 'Aichi', 'Kariya', 'Retail', '携帯電話ショップスタッフ', '携帯電話販売とプラン説明', '愛知', '刈谷', '小売', 1),
('Payroll clerk', 'Processing employee payroll and maintaining records.', 'Fukuoka', 'Kashii', 'Office', '給与計算係', '従業員給与処理と記録管理', '福岡', '香椎', '事務', 0),
('Sushi restaurant host', 'Greeting and seating customers in a sushi restaurant.', 'Tokyo', 'Tsukiji', 'Food', '寿司屋ホスト', '寿司屋での来客対応と案内', '東京', '築地', '飲食', 1),
('Shoe store salesperson', 'Fitting and selling shoes to customers.', 'Osaka', 'Abeno', 'Retail', '靴店販売員', '顧客への靴の試着と販売', '大阪', '阿倍野', '小売', 0),
('Administrative coordinator', 'Coordinating office procedures and staff.', 'Aichi', 'Anjo', 'Office', '管理調整係', 'オフィス手続きとスタッフの調整', '愛知', '安城', '事務', 1),
('Curry house staff', 'Preparing and serving curry dishes.', 'Fukuoka', 'Nakasu', 'Food', 'カレー店スタッフ', 'カレー料理の調理と提供', '福岡', '中洲', '飲食', 0),
('Drugstore clerk', 'Assisting customers and stocking shelves in a drugstore.', 'Tokyo', 'Kinshicho', 'Retail', 'ドラッグストア店員', 'ドラッグストアでの接客と商品補充', '東京', '錦糸町', '小売', 1),
('Legal secretary', 'Providing administrative support in a law office.', 'Osaka', 'Hommachi', 'Office', '法律事務所秘書', '法律事務所での管理サポート', '大阪', '本町', '事務', 0),
('Yakitori shop cook', 'Grilling and serving yakitori skewers.', 'Aichi', 'Toyokawa', 'Food', '焼き鳥屋調理師', '焼き鳥の調理と提供', '愛知', '豊川', '飲食', 1),
('Gift shop attendant', 'Selling souvenirs and gift items.', 'Fukuoka', 'Momochi', 'Retail', 'ギフトショップ店員', 'お土産や贈答品の販売', '福岡', 'ももち', '小売', 0),
('Customer service representative', 'Handling customer inquiries and complaints.', 'Tokyo', 'Nihombashi', 'Office', 'カスタマーサービス担当', '顧客からの問い合わせとクレーム対応', '東京', '日本橋', '事務', 1),
('Udon restaurant staff', 'Preparing and serving udon noodles.', 'Osaka', 'Fukushima', 'Food', 'うどん店スタッフ', 'うどんの調理と提供', '大阪', '福島', '飲食', 0),
('Cosmetics counter salesperson', 'Demonstrating and selling cosmetic products.', 'Aichi', 'Okazaki', 'Retail', '化粧品カウンター販売員', '化粧品のデモンストレーションと販売', '愛知', '岡崎', '小売', 1),
('File clerk', 'Organizing and maintaining company files and records.', 'Fukuoka', 'Hakozaki', 'Office', 'ファイリング係', '会社のファイルと記録の整理維持', '福岡', '箱崎', '事務', 0),
('Tempura restaurant chef', 'Preparing and cooking tempura dishes.', 'Tokyo', 'Asakusa', 'Food', '天ぷら屋料理人', '天ぷら料理の調理', '東京', '浅草', '飲食', 1),
('Sporting goods store clerk', 'Selling sports equipment and clothing.', 'Osaka', 'Namba', 'Retail', 'スポーツ用品店店員', 'スポーツ用品と衣料の販売', '大阪', '難波', '小売', 0),
('Inventory control clerk', 'Managing and tracking inventory levels.', 'Aichi', 'Handa', 'Office', '在庫管理係', '在庫レベルの管理と追跡', '愛知', '半田', '事務', 1),
('Yakiniku restaurant server', 'Taking orders and serving at a yakiniku restaurant.', 'Fukuoka', 'Yakuin', 'Food', '焼肉店サーバー', '焼肉店での注文取りと接客', '福岡', '薬院', '飲食', 0),
('Jewelry store associate', 'Selling and cleaning jewelry items.', 'Tokyo', 'Ginza', 'Retail', 'ジュエリーショップ販売員', 'ジュエリーの販売とクリーニング', '東京', '銀座', '小売', 1),
('Data analyst', 'Analyzing data and preparing reports.', 'Osaka', 'Yodoyabashi', 'Office', 'データアナリスト', 'データ分析とレポート作成', '大阪', '淀屋橋', '事務', 0),
('Kaiseki restaurant kitchen staff', 'Preparing ingredients for kaiseki cuisine.', 'Aichi', 'Sakae', 'Food', '懐石料理店キッチンスタッフ', '懐石料理の食材準備', '愛知', '栄', '飲食', 1),
('Home appliance store consultant', 'Advising customers on home appliance purchases.', 'Fukuoka', 'Nishijin', 'Retail', '家電量販店コンサルタント', '家電購入のアドバイス', '福岡', '西新', '小売', 0),
('Office assistant', 'Providing general support in an office environment.', 'Tokyo', 'Shinagawa', 'Office', 'オフィスアシスタント', 'オフィスでの一般的なサポート業務', '東京', '品川', '事務', 1),
('Okonomiyaki shop cook', 'Cooking and serving okonomiyaki.', 'Osaka', 'Tsuruhashi', 'Food', 'お好み焼き店調理師', 'お好み焼きの調理と提供', '大阪', '鶴橋', '飲食', 0),
('Furniture store salesperson', 'Selling furniture and home decor items.', 'Aichi', 'Kozoji', 'Retail', '家具店販売員', '家具とホームデコアイテムの販売', '愛知', '高蔵寺', '小売', 1),
('Accounting assistant', 'Assisting with financial record-keeping and reports.', 'Fukuoka', 'Ijiri', 'Office', '経理アシスタント', '財務記録管理とレポート作成の補助', '福岡', '井尻', '事務', 0),
('Ramen shop cook', 'Preparing and cooking ramen dishes.', 'Tokyo', 'Takadanobaba', 'Food', 'ラーメン店調理師', 'ラーメンの調理', '東京', '高田馬場', '飲食', 1),
('Eyewear store consultant', 'Assisting customers with eyeglass selection and fitting.', 'Osaka', 'Kyobashi', 'Retail', 'メガネショップコンサルタント', 'メガネの選択とフィッティング補助', '大阪', '京橋', '小売', 0),
('Human resources clerk', 'Assisting with HR-related paperwork and processes.', 'Aichi', 'Fujigaoka', 'Office', '人事事務員', '人事関連の書類作成と手続き補助', '愛知', '藤が丘', '事務', 0),
('Restaurant waiter', 'Taking orders and serving food in a restaurant.', 'Fukuoka', 'Hakata', 'Food', 'レストラン接客係', 'レストランでの注文取りと料理提供', '福岡', '博多', '飲食', 0),
('Convenience store clerk', 'Restocking shelves and operating the cash register.', 'Tokyo', 'Shinjuku', 'Retail', 'コンビニ店員', '商品補充とレジ操作', '東京', '新宿', '小売', 1),
('Data entry clerk', 'Inputting data into company systems.', 'Osaka', 'Namba', 'Office', 'データ入力係', '会社システムへのデータ入力', '大阪', '難波', '事務', 0),
('Sushi chef assistant', 'Preparing ingredients and assisting the main chef.', 'Aichi', 'Okazaki', 'Food', '寿司職人助手', '食材準備と主任シェフの補助', '愛知', '岡崎', '飲食', 1),
('Bookstore staff', 'Organizing books and assisting customers.', 'Fukuoka', 'Tenjin', 'Retail', '書店スタッフ', '本の整理と顧客対応', '福岡', '天神', '小売', 0),
('HR assistant', 'Handling employee records and recruitment support.', 'Tokyo', 'Akasaka', 'Office', '人事アシスタント', '従業員記録管理と採用支援', '東京', '赤坂', '事務', 1),
('Barista', 'Making and serving coffee in a specialty coffee shop.', 'Osaka', 'Shinsaibashi', 'Food', 'バリスタ', '専門コーヒーショップでのコーヒー提供', '大阪', '心斎橋', '飲食', 0),
('Electronics store salesperson', 'Selling and explaining electronic products.', 'Aichi', 'Sakae', 'Retail', '家電販売員', '電子製品の販売と説明', '愛知', '栄', '小売', 1),
('Accounting clerk', 'Processing invoices and financial data entry.', 'Fukuoka', 'Ohori', 'Office', '経理事務員', '請求書処理と財務データ入力', '福岡', '大濠', '事務', 0),
('Ramen shop staff', 'Preparing and serving ramen dishes.', 'Tokyo', 'Ikebukuro', 'Food', 'ラーメン店スタッフ', 'ラーメンの調理と提供', '東京', '池袋', '飲食', 1),
('Fashion boutique assistant', 'Advising customers on fashion choices.', 'Osaka', 'Tennoji', 'Retail', 'ファッションブティック助手', '顧客へのファッションアドバイス', '大阪', '天王寺', '小売', 0),
('Office manager', 'Overseeing office operations and staff.', 'Aichi', 'Toyota', 'Office', 'オフィスマネージャー', 'オフィス業務とスタッフの管理', '愛知', '豊田', '事務', 1),
('Izakaya server', 'Taking orders and serving in a Japanese pub.', 'Fukuoka', 'Nakasu', 'Food', '居酒屋サーバー', '居酒屋での注文取りと接客', '福岡', '中洲', '飲食', 0),
('Supermarket cashier', 'Operating cash registers and bagging groceries.', 'Tokyo', 'Kichijoji', 'Retail', 'スーパーマーケットレジ係', 'レジ操作と商品袋詰め', '東京', '吉祥寺', '小売', 1),
('Executive secretary', 'Providing administrative support to executives.', 'Osaka', 'Honmachi', 'Office', '秘書', '幹部への管理サポート提供', '大阪', '本町', '事務', 0),
('Bakery staff', 'Baking and selling bread and pastries.', 'Aichi', 'Kanayama', 'Food', 'ベーカリースタッフ', 'パンとペストリーの製造販売', '愛知', '金山', '飲食', 1),
('Department store sales associate', 'Assisting customers in various departments.', 'Fukuoka', 'Kokura', 'Retail', '百貨店販売員', '各売り場での顧客対応', '福岡', '小倉', '小売', 0),
('Receptionist', 'Greeting visitors and managing front desk operations.', 'Tokyo', 'Ginza', 'Office', '受付係', '来客対応とフロント業務管理', '東京', '銀座', '事務', 1),
('Soba restaurant cook', 'Preparing and cooking soba noodles.', 'Osaka', 'Kitashinchi', 'Food', 'そば屋調理師', 'そばの調理', '大阪', '北新地', '飲食', 0),
('Mobile phone shop staff', 'Selling phones and explaining service plans.', 'Aichi', 'Fujigaoka', 'Retail', '携帯ショップスタッフ', '携帯電話販売とプラン説明', '愛知', '藤が丘', '小売', 1),
('Logistics coordinator', 'Managing shipping and inventory records.', 'Fukuoka', 'Kashii', 'Office', '物流コーディネーター', '出荷と在庫記録の管理', '福岡', '香椎', '事務', 0),
('Dessert cafe staff', 'Preparing and serving desserts and drinks.', 'Tokyo', 'Harajuku', 'Food', 'デザートカフェスタッフ', 'デザートとドリンクの提供', '東京', '原宿', '飲食', 1),
('Shoe store clerk', 'Helping customers find and fit shoes.', 'Osaka', 'Amerikamura', 'Retail', '靴店店員', '顧客の靴選びと試着補助', '大阪', 'アメリカ村', '小売', 0),
('Administrative clerk', 'General office work and document management.', 'Aichi', 'Tsurumai', 'Office', '一般事務員', '一般事務作業と文書管理', '愛知', '鶴舞', '事務', 1),
('Yakitori shop assistant', 'Grilling and serving yakitori skewers.', 'Fukuoka', 'Akasaka', 'Food', '焼き鳥店アシスタント', '焼き鳥の調理と提供', '福岡', '赤坂', '飲食', 0),
('Gift shop attendant', 'Selling souvenirs and gift items.', 'Tokyo', 'Asakusa', 'Retail', '土産物店店員', 'お土産と贈答品の販売', '東京', '浅草', '小売', 1),
('Customer service representative', 'Handling customer inquiries via phone and email.', 'Osaka', 'Kyobashi', 'Office', 'カスタマーサービス担当', '電話とメールでの顧客対応', '大阪', '京橋', '事務', 0),
('Tempura restaurant chef', 'Preparing and frying tempura dishes.', 'Aichi', 'Fushimi', 'Food', '天ぷら店料理人', '天ぷらの調理', '愛知', '伏見', '飲食', 1),
('Sports equipment store staff', 'Advising on and selling sports gear.', 'Fukuoka', 'Momochi', 'Retail', 'スポーツ用品店スタッフ', 'スポーツ用品の販売とアドバイス', '福岡', 'ももち', '小売', 0),
('Marketing assistant', 'Supporting marketing campaigns and data analysis.', 'Tokyo', 'Roppongi', 'Office', 'マーケティングアシスタント', 'マーケティング活動とデータ分析の支援', '東京', '六本木', '事務', 1),
('Udon shop worker', 'Making and serving udon noodles.', 'Osaka', 'Dotonbori', 'Food', 'うどん店従業員', 'うどんの製造と提供', '大阪', '道頓堀', '飲食', 0),
('Jewelry store sales associate', 'Selling and showcasing jewelry items.', 'Aichi', 'Oasis 21', 'Retail', 'ジュエリーショップ販売員', 'ジュエリーの販売と展示', '愛知', 'オアシス21', '小売', 1),
('Payroll clerk', 'Processing employee payroll and related tasks.', 'Fukuoka', 'Yakuin', 'Office', '給与計算係', '従業員給与処理と関連業務', '福岡', '薬院', '事務', 0),
('Sushi restaurant host', 'Greeting and seating customers in a sushi restaurant.', 'Tokyo', 'Tsukiji', 'Food', '寿司屋ホスト', '寿司屋での接客と案内', '東京', '築地', '飲食', 1),
('Cosmetics counter consultant', 'Demonstrating and selling cosmetic products.', 'Osaka', 'Abeno', 'Retail', '化粧品カウンターコンサルタント', '化粧品の実演と販売', '大阪', 'あべの', '小売', 0),
('IT support assistant', 'Providing technical support to office staff.', 'Aichi', 'Sasashima', 'Office', 'ITサポートアシスタント', 'オフィススタッフへの技術サポート提供', '愛知', 'ささしま', '事務', 1),
('Okonomiyaki chef', 'Cooking and serving okonomiyaki dishes.', 'Fukuoka', 'Tenjin', 'Food', 'お好み焼き職人', 'お好み焼きの調理と提供', '福岡', '天神', '飲食', 0),
('Toy store clerk', 'Assisting customers and demonstrating toys.', 'Tokyo', 'Odaiba', 'Retail', 'おもちゃ屋店員', '顧客対応とおもちゃの実演', '東京', 'お台場', '小売', 1),
('Human resources coordinator', 'Assisting with recruitment and employee relations.', 'Osaka', 'Yodoyabashi', 'Office', '人事コーディネーター', '採用と従業員関係の支援', '大阪', '淀屋橋', '事務', 0),
('Shabu-shabu restaurant staff', 'Preparing ingredients and serving hot pot dishes.', 'Aichi', 'Sakae', 'Food', 'しゃぶしゃぶ店スタッフ', '材料準備と鍋料理の提供', '愛知', '栄', '飲食', 1),
('Camera shop salesperson', 'Selling and explaining camera equipment.', 'Fukuoka', 'Hakata', 'Retail', 'カメラ店販売員', 'カメラ機器の販売と説明', '福岡', '博多', '小売', 0),
('Office administrator', 'Managing office supplies and scheduling.', 'Tokyo', 'Nihombashi', 'Office', 'オフィス管理者', 'オフィス用品管理とスケジュール調整', '東京', '日本橋', '事務', 1),
('Ramen chef', 'Preparing and cooking ramen dishes.', 'Osaka', 'Namba', 'Food', 'ラーメン職人', 'ラーメンの調理', '大阪', '難波', '飲食', 0),
('Clothing store manager', 'Overseeing store operations and staff.', 'Aichi', 'Nagoya', 'Retail', '衣料品店マネージャー', '店舗運営とスタッフ管理', '愛知', '名古屋', '小売', 1),
('Accounting assistant', 'Assisting with financial records and reports.', 'Fukuoka', 'Tenjin', 'Office', '経理アシスタント', '財務記録と報告書の作成補助', '福岡', '天神', '事務', 0),
('Soba noodle maker', 'Making and preparing soba noodles.', 'Tokyo', 'Kanda', 'Food', 'そば打ち職人', 'そばの製造と準備', '東京', '神田', '飲食', 1),
('Electronics repair technician', 'Repairing and servicing electronic devices.', 'Osaka', 'Umeda', 'Retail', '電子機器修理技術者', '電子機器の修理とサービス', '大阪', '梅田', '小売', 0),
('Executive assistant', 'Providing high-level support to company executives.', 'Aichi', 'Marunouchi', 'Office', 'エグゼクティブアシスタント', '会社幹部への高度なサポート提供', '愛知', '丸の内', '事務', 1),
('Restaurant waiter', 'Taking orders and serving food in a restaurant.', 'Fukuoka', 'Hakata', 'Food', 'レストラン接客係', 'レストランでの注文取りと料理提供', '福岡', '博多', '飲食', 0),
('Convenience store clerk', 'Restocking shelves and operating the cash register.', 'Tokyo', 'Shinjuku', 'Retail', 'コンビニ店員', '商品補充とレジ操作', '東京', '新宿', '小売', 1),
('Data entry clerk', 'Inputting data into company databases.', 'Osaka', 'Namba', 'Office', 'データ入力係', '会社のデータベースへの情報入力', '大阪', '難波', '事務', 0),
('Sushi chef assistant', 'Preparing ingredients and assisting the main chef.', 'Aichi', 'Okazaki', 'Food', '寿司職人助手', '食材準備と主任シェフの補助', '愛知', '岡崎', '飲食', 1),
('Bookstore staff', 'Organizing books and assisting customers.', 'Fukuoka', 'Tenjin', 'Retail', '書店スタッフ', '本の整理と顧客対応', '福岡', '天神', '小売', 0),
('Human resources assistant', 'Helping with recruitment and employee management.', 'Tokyo', 'Marunouchi', 'Office', '人事アシスタント', '採用と従業員管理の補助', '東京', '丸の内', '事務', 1),
('Ramen shop cook', 'Preparing and cooking ramen dishes.', 'Osaka', 'Dotonbori', 'Food', 'ラーメン店調理師', 'ラーメンの調理と提供', '大阪', '道頓堀', '飲食', 0),
('Electronics store salesperson', 'Selling and explaining electronic products.', 'Aichi', 'Sakae', 'Retail', '家電販売員', '電化製品の販売と説明', '愛知', '栄', '小売', 1),
('Accounting clerk', 'Processing financial transactions and maintaining records.', 'Fukuoka', 'Momochi', 'Office', '経理事務員', '財務取引の処理と記録管理', '福岡', 'ももち', '事務', 0),
('Izakaya staff', 'Serving drinks and food in a Japanese pub.', 'Tokyo', 'Ikebukuro', 'Food', '居酒屋スタッフ', '居酒屋での飲食物の提供', '東京', '池袋', '飲食', 1),
('Department store sales associate', 'Assisting customers in various departments.', 'Osaka', 'Shinsaibashi', 'Retail', '百貨店販売員', '百貨店の各部門での顧客対応', '大阪', '心斎橋', '小売', 0),
('Executive secretary', 'Supporting senior management with administrative tasks.', 'Aichi', 'Toyota', 'Office', '秘書', '経営幹部の管理業務サポート', '愛知', '豊田', '事務', 1),
('Bakery staff', 'Baking and selling bread and pastries.', 'Fukuoka', 'Ohori', 'Food', 'パン屋スタッフ', 'パンとペイストリーの製造販売', '福岡', '大濠', '飲食', 0),
('Clothing boutique manager', 'Overseeing store operations and staff.', 'Tokyo', 'Ginza', 'Retail', '衣料品店マネージャー', '店舗運営とスタッフ管理', '東京', '銀座', '小売', 1),
('Legal assistant', 'Supporting lawyers with document preparation.', 'Osaka', 'Hommachi', 'Office', '法務アシスタント', '弁護士の文書作成サポート', '大阪', '本町', '事務', 0),
('Soba restaurant chef', 'Preparing and cooking soba noodle dishes.', 'Aichi', 'Handa', 'Food', 'そば屋料理人', 'そば料理の調理', '愛知', '半田', '飲食', 1),
('Supermarket cashier', 'Operating cash registers and bagging groceries.', 'Fukuoka', 'Kashii', 'Retail', 'スーパーマーケットレジ係', 'レジ操作と商品袋詰め', '福岡', '香椎', '小売', 0),
('Office manager', 'Coordinating office activities and supervising staff.', 'Tokyo', 'Roppongi', 'Office', 'オフィスマネージャー', 'オフィス業務の調整とスタッフ監督', '東京', '六本木', '事務', 1),
('Sushi restaurant host', 'Greeting and seating customers in a sushi restaurant.', 'Osaka', 'Tsuruhashi', 'Food', '寿司屋ホスト', '寿司屋での接客と案内', '大阪', '鶴橋', '飲食', 0),
('Shoe store clerk', 'Helping customers find and try on shoes.', 'Aichi', 'Ichinomiya', 'Retail', '靴店店員', '靴の接客と試着サポート', '愛知', '一宮', '小売', 1),
('Receptionist', 'Greeting visitors and answering phone calls.', 'Fukuoka', 'Akasaka', 'Office', '受付係', '来客対応と電話応対', '福岡', '赤坂', '事務', 0),
('Fast food crew member', 'Preparing and serving fast food orders.', 'Tokyo', 'Akihabara', 'Food', 'ファストフード店員', 'ファストフードの調理と提供', '東京', '秋葉原', '飲食', 1),
('Jewelry store associate', 'Selling and showcasing jewelry items.', 'Osaka', 'Tennoji', 'Retail', 'ジュエリーショップ販売員', 'ジュエリーの販売と展示', '大阪', '天王寺', '小売', 0),
('Payroll specialist', 'Processing employee payroll and benefits.', 'Aichi', 'Anjo', 'Office', '給与計算担当者', '従業員の給与計算と福利厚生処理', '愛知', '安城', '事務', 1),
('Cafe barista', 'Preparing and serving coffee drinks.', 'Fukuoka', 'Nishijin', 'Food', 'カフェバリスタ', 'コーヒー飲料の準備と提供', '福岡', '西新', '飲食', 0),
('Sports equipment salesperson', 'Advising customers on sports gear purchases.', 'Tokyo', 'Kichijoji', 'Retail', 'スポーツ用品販売員', 'スポーツ用品の販売アドバイス', '東京', '吉祥寺', '小売', 1),
('Administrative coordinator', 'Coordinating office logistics and scheduling.', 'Osaka', 'Yodoyabashi', 'Office', '管理調整係', 'オフィスの物流とスケジュール調整', '大阪', '淀屋橋', '事務', 0),
('Teppanyaki chef', 'Cooking and performing at a teppanyaki grill.', 'Aichi', 'Toyohashi', 'Food', '鉄板焼きシェフ', '鉄板焼きの調理とパフォーマンス', '愛知', '豊橋', '飲食', 1),
('Cosmetics counter representative', 'Demonstrating and selling cosmetic products.', 'Fukuoka', 'Yakuin', 'Retail', '化粧品カウンター担当', '化粧品のデモンストレーションと販売', '福岡', '薬院', '小売', 0),
('Project assistant', 'Supporting project managers with various tasks.', 'Tokyo', 'Shinagawa', 'Office', 'プロジェクトアシスタント', 'プロジェクトマネージャーの業務支援', '東京', '品川', '事務', 1),
('Soba noodle maker', 'Making and preparing soba noodles.', 'Osaka', 'Kyobashi', 'Food', 'そば打ち職人', 'そばの製麺と準備', '大阪', '京橋', '飲食', 0),
('Home appliance salesperson', 'Selling and explaining home appliances.', 'Aichi', 'Kasugai', 'Retail', '家電販売員', '家電製品の販売と説明', '愛知', '春日井', '小売', 1),
('Customer service representative', 'Handling customer inquiries and complaints.', 'Fukuoka', 'Nakasu', 'Office', 'カスタマーサービス担当', '顧客の問い合わせと苦情対応', '福岡', '中洲', '事務', 0),
('Dessert cafe staff', 'Preparing and serving desserts and sweets.', 'Tokyo', 'Harajuku', 'Food', 'デザートカフェスタッフ', 'デザートとスイーツの準備と提供', '東京', '原宿', '飲食', 1),
('Toy store clerk', 'Assisting customers with toy selections.', 'Osaka', 'Nippombashi', 'Retail', 'おもちゃ店店員', 'おもちゃの選択補助', '大阪', '日本橋', '小売', 0),
('Data analyst', 'Analyzing and interpreting complex data sets.', 'Aichi', 'Obu', 'Office', 'データアナリスト', '複雑なデータセットの分析と解釈', '愛知', '大府', '事務', 1),
('Udon restaurant cook', 'Preparing and cooking udon noodle dishes.', 'Fukuoka', 'Yoshizuka', 'Food', 'うどん店調理師', 'うどん料理の調理', '福岡', '吉塚', '飲食', 0),
('Furniture store salesperson', 'Selling and arranging furniture displays.', 'Tokyo', 'Koto', 'Retail', '家具店販売員', '家具の販売とディスプレイ配置', '東京', '江東', '小売', 1),
('Marketing coordinator', 'Assisting with marketing campaigns and events.', 'Osaka', 'Kishiwada', 'Office', 'マーケティングコーディネーター', 'マーケティングキャンペーンとイベントの補助', '大阪', '岸和田', '事務', 0),
('Yakitori chef', 'Grilling and serving yakitori skewers.', 'Aichi', 'Kariya', 'Food', '焼き鳥シェフ', '焼き鳥の調理と提供', '愛知', '刈谷', '飲食', 1),
('Book store manager', 'Overseeing bookstore operations and inventory.', 'Fukuoka', 'Kokura', 'Retail', '書店マネージャー', '書店の運営と在庫管理', '福岡', '小倉', '小売', 0),
('IT support specialist', 'Providing technical support to office staff.', 'Tokyo', 'Osaki', 'Office', 'ITサポートスペシャリスト', 'オフィススタッフへの技術サポート提供', '東京', '大崎', '事務', 1),
('Ice cream shop staff', 'Scooping and serving ice cream.', 'Osaka', 'Esaka', 'Food', 'アイスクリームショップスタッフ', 'アイスクリームのスクープと提供', '大阪', '江坂', '飲食', 0),
('Camera store associate', 'Advising customers on camera and photography equipment.', 'Aichi', 'Chikusa', 'Retail', 'カメラ店販売員', 'カメラと写真機材のアドバイス', '愛知', '千種', '小売', 1),
('Executive assistant', 'Providing high-level support to executives.', 'Fukuoka', 'Chihaya', 'Office', 'エグゼクティブアシスタント', '経営幹部への高度なサポート提供', '福岡', '千早', '事務', 0),
('Sushi restaurant manager', 'Managing staff and operations in a sushi restaurant.', 'Tokyo', 'Tsukiji', 'Food', '寿司屋店長', '寿司屋のスタッフと運営管理', '東京', '築地', '飲食', 1),
('Mobile phone store representative', 'Selling mobile phones and service plans.', 'Osaka', 'Abeno', 'Retail', '携帯電話ショップ販売員', '携帯電話と通信プランの販売', '大阪', 'あべの', '小売', 0),
('Human resources coordinator', 'Assisting with employee relations and recruitment.', 'Aichi', 'Nishio', 'Office', '人事コーディネーター', '従業員関係と採用の補助', '愛知', '西尾', '事務', 1);